-- НОВЫЙ СКРИПТ В MYDB.SQLITE.
-- ДАТА: 2 ДЕК. 2022 Г.
-- ВРЕМЯ: 10:58:43
 
 

UPDATE
	INVENT
SET
	REMAIN = SUMITOG.ITOG
FROM
	(
	SELECT
		* ,
        CASE WHEN opcode = '50'
       THEN (REMAIN - "SUM(CQUANT)" )
       ELSE (REMAIN + "SUM(CQUANT)" )
       END AS ITOG
	FROM
		SUMMPROD
) AS SUMITOG
WHERE
	INVENT.INVENTCODE = SUMITOG.CODE